apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: service-ip
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 21
      name: command
    - port: 21100
      name: port21100
    - port: 21101
      name: port21101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 21100
          - containerPort: 21101